server:
  port: 8081

spring:
  application:
    name: core-business-engine
  threads:
    virtual:
      enabled: true # Enables Loom Virtual Threads
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/b2b_qcomm}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:adminpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    function:
      definition: processEvaluatedOrder
    stream:
      bindings:
        processEvaluatedOrder-in-0:
          destination: b2b.wholesale.order.evaluated
          group: core-b2b-group
          content-type: application/json
          consumer:
            max-attempts: 3
        checkoutProcessor-out-0:
          destination: b2b.checkout.events
          content-type: application/json
        b2b-wholesale-out-0:
          destination: b2b.wholesale.order.placed
          content-type: application/json
      kafka:
        bindings:
          processEvaluatedOrder-in-0:
            consumer:
              enableDlq: true
              dlqName: b2b.wholesale.order.evaluated.DLQ
              autoCommitOnError: false
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
