spring:
  config:
    activate:
      on-profile: cloud-production

  # Cloud Managed Target Infrastructure Swaps (Scale Targets)
  datasource:
    url: jdbc:postgresql://${CLOUD_DB_HOST}:5432/production_enterprise_db
    username: ${CLOUD_DB_USER}
    password: ${CLOUD_DB_PASS}

  data:
    mongodb:
      uri: mongodb://${CLOUD_MONGO_HOST}:27017/production_shared_db
    redis:
      host: ${CLOUD_REDIS_HOST}
      port: 6379

  # Swapping Underlying Event Transport Infrastructure with Zero Java Re-writes
  cloud:
    stream:
      bindings:
        outboxRelayProcessor-out-0:
          destination: production-enterprise-order-events
          binder: enterprise-cloud-binder
      binders:
        enterprise-cloud-binder:
          # For GCP Deployment: Swap to "pubsub"
          # For Azure Deployment: Swap to "eventhub"
          type: pubsub 

  ai:
    ollama:
      enabled: false # Turn off local model dependencies
    vertexai:        # For GCP Deployment
      enabled: true
      project-id: ${GCP_PROJECT_ID}
      location: ${GCP_REGION}
