import { Platform, StyleSheet } from "react-native";
import { THEME } from "./constants";

// ----------------------------------------------------
// CYBER-INDUSTRIAL STYLE SYSTEM (hsl matching style.css)
// ----------------------------------------------------
const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: THEME.bgBody,
	},
	header: {
		backgroundColor: THEME.bgDark,
		borderBottomWidth: 1,
		borderBottomColor: THEME.borderColor,
		paddingHorizontal: 16,
		paddingTop: Platform.OS === "ios" ? 12 : 16,
		paddingBottom: 16,
	},
	brandRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 8,
	},
	logoText: {
		fontFamily: Platform.OS === "ios" ? "Outfit" : "sans-serif",
		fontWeight: "800",
		fontSize: 18,
		letterSpacing: -0.5,
		color: THEME.textPrimary,
	},
	connectionBadge: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "rgba(255, 255, 255, 0.04)",
		borderColor: THEME.borderColor,
		borderWidth: 1,
		borderRadius: 12,
		paddingVertical: 4,
		paddingHorizontal: 10,
	},
	ledIndicator: {
		width: 6,
		height: 6,
		borderRadius: 3,
		marginRight: 6,
	},
	connectionText: {
		fontSize: 10,
		fontWeight: "700",
		letterSpacing: 0.5,
	},
	subHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginTop: 4,
	},
	roleContainer: {
		flexDirection: "row",
		alignItems: "center",
	},
	roleText: {
		color: THEME.textSecondary,
		fontSize: 11,
		fontWeight: "700",
		marginLeft: 6,
		letterSpacing: 0.3,
	},
	settingsBtn: {
		padding: 4,
		backgroundColor: "rgba(255, 255, 255, 0.05)",
		borderRadius: 8,
	},
	metricsContainer: {
		flexDirection: "row",
		backgroundColor: "rgba(7, 10, 19, 0.5)",
		borderBottomWidth: 1,
		borderBottomColor: THEME.borderColor,
		paddingVertical: 12,
	},
	metricItem: {
		flex: 1,
		alignItems: "center",
		borderRightWidth: 1,
		borderRightColor: THEME.borderColor,
	},
	metricLabel: {
		color: THEME.textMuted,
		fontSize: 8,
		fontWeight: "700",
		letterSpacing: 0.5,
		marginBottom: 2,
	},
	metricValue: {
		fontSize: 15,
		fontWeight: "800",
		fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
	},
	storeSelectorContainer: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingVertical: 10,
		backgroundColor: "rgba(11, 15, 25, 0.4)",
		borderBottomWidth: 1,
		borderBottomColor: THEME.borderColor,
	},
	storeSelectorLabel: {
		color: THEME.textSecondary,
		fontSize: 12,
		fontWeight: "600",
	},
	storePillRow: {
		flexDirection: "row",
		gap: 8,
	},
	storePill: {
		paddingVertical: 5,
		paddingHorizontal: 12,
		borderRadius: 14,
		backgroundColor: "rgba(255, 255, 255, 0.04)",
		borderColor: THEME.borderColor,
		borderWidth: 1,
	},
	storePillActive: {
		backgroundColor: THEME.inventory,
		borderColor: THEME.inventory,
	},
	storePillText: {
		color: THEME.textSecondary,
		fontSize: 11,
		fontWeight: "700",
	},
	storePillTextActive: {
		color: THEME.bgDark,
	},
	content: {
		padding: 16,
		paddingBottom: 80,
	},
	tabContent: {
		gap: 16,
	},
	sectionHeaderRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 4,
	},
	sectionTitle: {
		color: THEME.textPrimary,
		fontSize: 14,
		fontWeight: "700",
		letterSpacing: 0.2,
	},
	backupRunningBadge: {
		backgroundColor: THEME.customerGlow,
		borderColor: THEME.customer,
		borderWidth: 1,
		borderRadius: 6,
		paddingVertical: 2,
		paddingHorizontal: 6,
	},
	backupRunningText: {
		color: THEME.customer,
		fontSize: 8,
		fontWeight: "800",
	},
	emptyContainer: {
		backgroundColor: THEME.bgCard,
		borderColor: THEME.borderColor,
		borderWidth: 1,
		borderRadius: 16,
		padding: 32,
		alignItems: "center",
		justifyContent: "center",
		gap: 12,
	},
	emptyText: {
		color: THEME.textPrimary,
		fontSize: 16,
		fontWeight: "700",
	},
	emptySubText: {
		color: THEME.textSecondary,
		fontSize: 12,
		textAlign: "center",
		lineHeight: 16,
	},
	slaAlertBanner: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: THEME.admin,
		borderRadius: 10,
		padding: 10,
	},
	slaAlertText: {
		color: "#070a13",
		fontWeight: "800",
		fontSize: 11,
	},
	orderCard: {
		backgroundColor: THEME.bgCard,
		borderRadius: 16,
		padding: 16,
		borderWidth: 1,
		borderColor: THEME.borderColor,
		gap: 12,
	},
	orderCardCritical: {
		borderColor: THEME.admin,
		borderWidth: 1.5,
		backgroundColor: "rgba(239, 68, 68, 0.05)",
	},
	orderCardHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	orderIdText: {
		color: THEME.textPrimary,
		fontSize: 16,
		fontWeight: "800",
	},
	slaContainer: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "rgba(255, 255, 255, 0.04)",
		borderRadius: 8,
		paddingVertical: 4,
		paddingHorizontal: 8,
		gap: 4,
	},
	slaText: {
		color: THEME.textSecondary,
		fontSize: 11,
		fontWeight: "700",
		fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
	},
	slaTextCritical: {
		color: THEME.admin,
		fontWeight: "800",
	},
	orderMetadata: {
		flexDirection: "row",
		justifyContent: "space-between",
	},
	metaText: {
		color: THEME.textSecondary,
		fontSize: 12,
	},
	boldText: {
		color: THEME.textPrimary,
		fontWeight: "700",
	},
	itemsPreviewRow: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 6,
	},
	itemEmojiBadge: {
		backgroundColor: "rgba(255, 255, 255, 0.03)",
		borderRadius: 6,
		borderWidth: 1,
		borderColor: THEME.borderColor,
		paddingVertical: 4,
		paddingHorizontal: 8,
	},
	emojiBadgeText: {
		fontSize: 10,
		color: THEME.textPrimary,
		fontWeight: "600",
	},
	pickButton: {
		backgroundColor: THEME.inventory,
		borderRadius: 10,
		paddingVertical: 10,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		gap: 8,
		shadowColor: THEME.inventory,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 4,
	},
	pickButtonText: {
		color: "#070a13",
		fontWeight: "800",
		fontSize: 12,
		letterSpacing: 0.5,
	},
	card: {
		backgroundColor: THEME.bgCard,
		borderRadius: 16,
		padding: 16,
		borderWidth: 1,
		borderColor: THEME.borderColor,
		gap: 12,
	},
	cardTitle: {
		color: THEME.textPrimary,
		fontSize: 15,
		fontWeight: "800",
	},
	cardHeaderRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	cardDescription: {
		color: THEME.textSecondary,
		fontSize: 11,
		lineHeight: 16,
	},
	inputLabel: {
		color: THEME.textSecondary,
		fontSize: 11,
		fontWeight: "700",
		letterSpacing: 0.3,
		marginTop: 4,
	},
	pillInputRow: {
		flexDirection: "row",
		gap: 8,
	},
	miniPill: {
		flex: 1,
		paddingVertical: 8,
		borderRadius: 8,
		alignItems: "center",
		backgroundColor: "rgba(255, 255, 255, 0.04)",
		borderWidth: 1,
		borderColor: THEME.borderColor,
	},
	miniPillActive: {
		backgroundColor: THEME.inventoryGlow,
		borderColor: THEME.inventory,
	},
	miniPillText: {
		color: THEME.textPrimary,
		fontSize: 12,
		fontWeight: "700",
	},
	dispatchDestCard: {
		backgroundColor: "rgba(7, 10, 19, 0.6)",
		borderRadius: 8,
		padding: 10,
		borderColor: THEME.borderColor,
		borderWidth: 1,
	},
	dispatchDestText: {
		color: THEME.engine,
		fontWeight: "800",
		fontSize: 12,
		fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
	},
	itemPillScroller: {
		paddingVertical: 4,
	},
	itemSelectPill: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "rgba(255, 255, 255, 0.04)",
		borderWidth: 1,
		borderColor: THEME.borderColor,
		borderRadius: 8,
		paddingVertical: 8,
		paddingHorizontal: 12,
		marginRight: 8,
		gap: 6,
	},
	itemSelectPillActive: {
		backgroundColor: THEME.inventoryGlow,
		borderColor: THEME.inventory,
	},
	itemSelectEmoji: {
		fontSize: 14,
	},
	itemSelectText: {
		color: THEME.textPrimary,
		fontSize: 11,
		fontWeight: "600",
	},
	qtyContainer: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	qtyBtn: {
		backgroundColor: "rgba(255, 255, 255, 0.05)",
		borderRadius: 8,
		width: 38,
		height: 38,
		alignItems: "center",
		justifyContent: "center",
		borderColor: THEME.borderColor,
		borderWidth: 1,
	},
	qtyBtnText: {
		color: THEME.textPrimary,
		fontWeight: "700",
		fontSize: 11,
	},
	qtyDisplayBox: {
		flex: 1,
		backgroundColor: "rgba(7, 10, 19, 0.6)",
		borderColor: THEME.borderColor,
		borderWidth: 1,
		borderRadius: 8,
		height: 38,
		alignItems: "center",
		justifyContent: "center",
	},
	qtyDisplayText: {
		color: THEME.inventory,
		fontSize: 16,
		fontWeight: "800",
		fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
	},
	dispatchSubmitBtn: {
		backgroundColor: THEME.customer,
		borderRadius: 10,
		paddingVertical: 12,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		gap: 8,
		shadowColor: THEME.customer,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 4,
		marginTop: 8,
	},
	dispatchSubmitBtnText: {
		color: "#070a13",
		fontWeight: "800",
		fontSize: 12,
		letterSpacing: 0.5,
	},
	resultHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		borderBottomWidth: 1,
		borderBottomColor: THEME.borderColor,
		paddingBottom: 8,
	},
	resultTitle: {
		fontSize: 12,
		fontWeight: "800",
		letterSpacing: 0.5,
	},
	resultTime: {
		fontSize: 10,
		color: THEME.textMuted,
	},
	resultGrid: {
		gap: 6,
	},
	resultRow: {
		flexDirection: "row",
		justifyContent: "space-between",
	},
	resultLabel: {
		color: THEME.textSecondary,
		fontSize: 11,
	},
	resultVal: {
		color: THEME.textPrimary,
		fontSize: 11,
		fontWeight: "700",
	},
	occupancyGaugeContainer: {
		backgroundColor: "rgba(7, 10, 19, 0.5)",
		borderRadius: 12,
		padding: 12,
		borderWidth: 1,
		borderColor: THEME.borderColor,
	},
	occupancyMetricBox: {
		alignItems: "center",
		marginBottom: 8,
	},
	occupancyLabel: {
		color: THEME.textMuted,
		fontSize: 8,
		fontWeight: "700",
		letterSpacing: 0.5,
	},
	occupancyValue: {
		fontSize: 24,
		fontWeight: "800",
		marginVertical: 2,
		fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
	},
	occupancySub: {
		color: THEME.textSecondary,
		fontSize: 9,
		fontWeight: "600",
	},
	progressTrackBar: {
		height: 6,
		backgroundColor: "rgba(255, 255, 255, 0.05)",
		borderRadius: 3,
		overflow: "hidden",
	},
	progressBarFill: {
		height: "100%",
		borderRadius: 3,
	},
	overflowSuccessCard: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: THEME.customer,
		borderRadius: 10,
		padding: 12,
	},
	overflowSuccessTitle: {
		color: "#070a13",
		fontWeight: "800",
		fontSize: 12,
	},
	overflowSuccessSub: {
		color: "rgba(7, 10, 19, 0.7)",
		fontSize: 10,
		fontWeight: "600",
	},
	resetScaleBtn: {
		backgroundColor: "#070a13",
		paddingVertical: 4,
		paddingHorizontal: 8,
		borderRadius: 6,
	},
	resetScaleBtnText: {
		color: THEME.textPrimary,
		fontSize: 9,
		fontWeight: "800",
	},
	scaleActionBtn: {
		backgroundColor: THEME.inventory,
		borderRadius: 10,
		paddingVertical: 12,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		gap: 8,
	},
	scalingIndicatorRow: {
		flexDirection: "row",
		alignItems: "center",
	},
	scaleActionBtnText: {
		color: "#070a13",
		fontWeight: "800",
		fontSize: 12,
		letterSpacing: 0.3,
	},
	rosterStatusContainer: {
		backgroundColor: "rgba(7, 10, 19, 0.5)",
		borderRadius: 12,
		padding: 12,
		borderWidth: 1,
		borderColor: THEME.borderColor,
		gap: 8,
	},
	rosterLabel: {
		color: THEME.textMuted,
		fontSize: 8,
		fontWeight: "700",
		letterSpacing: 0.5,
		textAlign: "center",
	},
	rosterStatusRow: {
		flexDirection: "row",
		justifyContent: "space-around",
	},
	rosterStatItem: {
		alignItems: "center",
	},
	rosterStatNum: {
		fontSize: 20,
		fontWeight: "800",
		color: THEME.textPrimary,
		fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
	},
	rosterStatLabel: {
		fontSize: 9,
		color: THEME.textSecondary,
		fontWeight: "600",
		marginTop: 2,
	},
	deployPulseAnimationContainer: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		marginTop: 4,
		paddingTop: 8,
		borderTopWidth: 1,
		borderTopColor: THEME.borderColor,
	},
	pulseNode: {
		width: 8,
		height: 8,
		borderRadius: 4,
		backgroundColor: THEME.customer,
	},
	pulseText: {
		color: THEME.customer,
		fontSize: 9,
		fontWeight: "700",
	},
	telemetryGrid: {
		gap: 8,
	},
	telemetryRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		borderBottomWidth: 1,
		borderBottomColor: "rgba(255, 255, 255, 0.02)",
		paddingBottom: 6,
	},
	telemetryLabel: {
		color: THEME.textSecondary,
		fontSize: 11,
	},
	telemetryVal: {
		color: THEME.textPrimary,
		fontSize: 11,
		fontWeight: "700",
	},
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0, 0, 0, 0.75)",
		justifyContent: "center",
		alignItems: "center",
		padding: 16,
	},
	pickModalContainer: {
		backgroundColor: THEME.bgBody,
		borderColor: THEME.borderColor,
		borderWidth: 1,
		borderRadius: 16,
		width: "100%",
		maxHeight: "85%",
		padding: 16,
		gap: 16,
	},
	pickModalHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		borderBottomWidth: 1,
		borderBottomColor: THEME.borderColor,
		paddingBottom: 12,
	},
	pickModalTitle: {
		fontSize: 16,
		fontWeight: "800",
		color: THEME.textPrimary,
	},
	pickModalSub: {
		color: THEME.textSecondary,
		fontSize: 11,
	},
	closeModalBtn: {
		padding: 4,
	},
	checklistTitle: {
		color: THEME.textMuted,
		fontSize: 10,
		fontWeight: "800",
		letterSpacing: 0.5,
	},
	checklistScroll: {
		flexGrow: 0,
		maxHeight: "50%",
	},
	checkItemRow: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "rgba(255, 255, 255, 0.02)",
		borderColor: THEME.borderColor,
		borderWidth: 1,
		borderRadius: 10,
		padding: 12,
		marginBottom: 8,
		gap: 10,
	},
	checkItemRowChecked: {
		borderColor: THEME.customer,
		backgroundColor: THEME.customerGlow,
	},
	checkbox: {
		width: 20,
		height: 20,
		borderRadius: 6,
		borderWidth: 1.5,
		borderColor: THEME.textSecondary,
		alignItems: "center",
		justifyContent: "center",
	},
	checkboxChecked: {
		borderColor: THEME.customer,
		backgroundColor: THEME.customer,
	},
	itemNameText: {
		color: THEME.textPrimary,
		fontSize: 13,
		fontWeight: "600",
	},
	itemNameTextChecked: {
		color: THEME.textSecondary,
		textDecorationLine: "line-through",
	},
	itemTagRow: {
		flexDirection: "row",
		gap: 6,
		marginTop: 4,
	},
	categoryBadge: {
		backgroundColor: "rgba(255, 255, 255, 0.05)",
		borderRadius: 4,
		paddingVertical: 1,
		paddingHorizontal: 4,
	},
	categoryBadgeText: {
		color: THEME.textSecondary,
		fontSize: 8,
		fontWeight: "700",
	},
	perishableBadge: {
		backgroundColor: "rgba(6, 182, 212, 0.1)",
		borderRadius: 4,
		paddingVertical: 1,
		paddingHorizontal: 4,
	},
	perishableBadgeText: {
		color: THEME.engine,
		fontSize: 8,
		fontWeight: "800",
	},
	itemQtyText: {
		color: THEME.textPrimary,
		fontWeight: "800",
		fontSize: 14,
		fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
	},
	handoverFormContainer: {
		gap: 10,
		borderTopWidth: 1,
		borderTopColor: THEME.borderColor,
		paddingTop: 12,
	},
	textInput: {
		backgroundColor: "rgba(255, 255, 255, 0.03)",
		borderColor: THEME.borderColor,
		borderWidth: 1,
		borderRadius: 8,
		paddingVertical: 8,
		paddingHorizontal: 12,
		color: THEME.textPrimary,
		fontSize: 13,
	},
	handoverBtnRow: {
		flexDirection: "row",
		gap: 8,
	},
	handoverBtn: {
		flex: 1,
		borderRadius: 8,
		paddingVertical: 12,
		alignItems: "center",
		justifyContent: "center",
	},
	handoverBtnError: {
		backgroundColor: "rgba(239, 68, 68, 0.15)",
		borderColor: THEME.admin,
		borderWidth: 1,
	},
	handoverBtnErrorText: {
		color: THEME.admin,
		fontWeight: "800",
		fontSize: 11,
	},
	handoverBtnSuccess: {
		backgroundColor: THEME.inventory,
		flexDirection: "row",
		gap: 6,
	},
	handoverBtnText: {
		color: "#070a13",
		fontWeight: "800",
		fontSize: 11,
	},
	settingsModalCard: {
		backgroundColor: THEME.bgBody,
		borderColor: THEME.borderColor,
		borderWidth: 1,
		borderRadius: 16,
		width: "100%",
		padding: 16,
		gap: 16,
	},
	modalHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		borderBottomWidth: 1,
		borderBottomColor: THEME.borderColor,
		paddingBottom: 8,
	},
	settingsTitle: {
		fontSize: 15,
		fontWeight: "800",
		color: THEME.textPrimary,
	},
	settingsScrollContent: {
		gap: 12,
	},
	settingsToggleRow: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "rgba(255, 255, 255, 0.02)",
		padding: 10,
		borderRadius: 10,
		borderColor: THEME.borderColor,
		borderWidth: 1,
	},
	toggleLabel: {
		color: THEME.textPrimary,
		fontSize: 12,
		fontWeight: "700",
	},
	toggleDesc: {
		color: THEME.textSecondary,
		fontSize: 9,
		marginTop: 2,
		paddingRight: 10,
	},
	bffConfigArea: {
		gap: 10,
	},
	testBtn: {
		backgroundColor: THEME.customer,
		paddingVertical: 10,
		borderRadius: 8,
		alignItems: "center",
		justifyContent: "center",
		flexDirection: "row",
		gap: 6,
		marginTop: 4,
	},
	testBtnText: {
		color: "#070a13",
		fontWeight: "800",
		fontSize: 11,
	},
	celebrationCard: {
		backgroundColor: THEME.bgDark,
		borderColor: "#fbbf24",
		borderWidth: 2,
		borderRadius: 24,
		padding: 24,
		alignItems: "center",
		width: "90%",
		gap: 16,
		shadowColor: "#fbbf24",
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.5,
		shadowRadius: 20,
		elevation: 10,
	},
	celebrationFlash: {
		color: "#fbbf24",
		fontSize: 18,
		fontWeight: "900",
		letterSpacing: 2,
	},
	badgeRing: {
		width: 120,
		height: 120,
		borderRadius: 60,
		backgroundColor: "rgba(251, 191, 36, 0.1)",
		borderColor: "#fbbf24",
		borderWidth: 2.5,
		alignItems: "center",
		justifyContent: "center",
	},
	celebrationTitle: {
		color: THEME.textPrimary,
		fontSize: 15,
		fontWeight: "800",
		letterSpacing: 0.5,
	},
	celebrationSub: {
		color: THEME.textSecondary,
		fontSize: 11,
		textAlign: "center",
		lineHeight: 16,
	},
	celebrationBtn: {
		backgroundColor: "#fbbf24",
		paddingVertical: 12,
		paddingHorizontal: 24,
		borderRadius: 10,
		width: "100%",
		alignItems: "center",
	},
	celebrationBtnText: {
		color: "#070a13",
		fontWeight: "900",
		fontSize: 12,
	},
	tabBar: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		height: 56,
		backgroundColor: THEME.bgDark,
		borderTopWidth: 1,
		borderTopColor: THEME.borderColor,
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
	},
	tabBarItem: {
		alignItems: "center",
		justifyContent: "center",
		gap: 4,
		flex: 1,
		height: "100%",
	},
	tabBarItemActive: {
		borderTopWidth: 2,
		borderTopColor: THEME.inventory,
	},
	tabBarText: {
		fontSize: 8,
		fontWeight: "700",
		color: THEME.textSecondary,
		letterSpacing: 0.3,
	},
	tabBarTextActive: {
		color: THEME.inventory,
	},
});

export default styles;
