global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8083']

  - job_name: 'platform-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['platform-gateway:8080']

  - job_name: 'core-business-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['core-business-engine:8081']

  - job_name: 'notification-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-engine:8082']
