spring.datasource.url=jdbc:postgresql://localhost:5420/swiss_db?sslmode=${DB_SSL_MODE:require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:swisssecure2026}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
